# Generated by Django 3.1.3 on 2023-04-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20230417_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='descricao',
            field=models.CharField(default='', max_length=300),
        ),
    ]
