# Generated by Django 3.1.3 on 2023-05-11 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='videos.categoria'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='cor',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='video',
            name='titulo',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
